class Solution {
public:
    vector<string> removeInvalidParentheses(string s) {
       unordered_set<string> res;
               queue<string> q;
                       unordered_set<string> visited;
                               q.push(s);
                                       visited.insert(s);
                                               bool found = false;
                                                       while (!q.empty()) {
                                                                   int sz = q.size();
                                                                               for (int i = 0; i < sz; ++i) {
                                                                                               string cur = q.front(); q.pop();
                                                                                                               if (isValid(cur)) {
                                                                                                                                   res.insert(cur);
                                                                                                                                                       found = true;
                                                                                                                                                                       }
                                                                                                                                                                                       if (found) continue; // only process current level for minimum removals
                                                                                                                                                                                                       for (int j = 0; j < cur.size(); ++j) {
                                                                                                                                                                                                                           if (cur[j] != '(' && cur[j] != ')') continue;
                                                                                                                                                                                                                                               string next = cur.substr(0, j) + cur.substr(j + 1);
                                                                                                                                                                                                                                                                   if (!visited.count(next)) {
                                                                                                                                                                                                                                                                                           visited.insert(next);
                                                                                                                                                                                                                                                                                                                   q.push(next);
                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                               if (found) break;
                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                               return vector<string>(res.begin(), res.end());
                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                   private:
                                                                                                                                                                                                                                                                                                                                                                                                       bool isValid(const string& s) {
                                                                                                                                                                                                                                                                                                                                                                                                               int count = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                       for (char c : s) {
                                                                                                                                                                                                                                                                                                                                                                                                                                   if (c == '(') ++count;
                                                                                                                                                                                                                                                                                                                                                                                                                                               else if (c == ')') {
                                                                                                                                                                                                                                                                                                                                                                                                                                                               if (--count < 0) return false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           return count == 0; 
    }
};